export interface PropertyModel {
  address: string;
  agent_note?: string;
  amenities: string[];
  allows_marijuana: boolean;
  available_at: string;
  bathrooms: number;
  bedrooms: number;
  building?: string;
  created_at: Date | string;
  description?: string;
  email: string;
  facilities?: string[];
  floor?: number;
  furnished: string;
  hot_deal: boolean;
  id: string;
  images?: string[];
  img: string;
  location: string;
  name: string;
  option: string[];
  ownership: string;
  phone?: string;
  price?: string;
  property_id: string;
  rental_price?: string;
  ref?: string;
  size?: string;
  stories: number;
  sub_district: string;
  transfer_fees: string;
  type: string;
  unit_number?: string;
  updated_at: Date | string;
  useable_area: string;
  views?: string[];
}